### ISSUE TITLE
Compatibility with krystal horizontal layout plug in

### ISSUE THREAD

**Issue by arunnbabu81** [cdruan/tw5-captivate#1]
Thanks for this excellent theme. You might not have released it for public use yet. So take these as just my suggestions. 

I use krystal horizontal layout plug-in in some of my my wikis. I wish to use this theme in those wikis. But topbar contents in krystal and this theme are different. I like the the way its done in krystal to open 'Open' 'Recent' tiddlers as dropdown as suggested in these links [1 ](https://github.com/crazko/krystal/issues/21#issuecomment-754664144) and [2 ](https://github.com/crazko/krystal/issues/21#issuecomment-755580770). Can this be done  if i am using your theme. Even if this is not added into the theme, can you suggest some hacks so that,  i can implement it?

**Comment by cdruan** [comment]
Do you want to use krystal layout but would like to incorporate colors generated by this theme? If so, here are two easy options:

- Import both theme/plugins in one wiki. From my theme, press Ctrl-Shift-L to switch the active layout to "Default Page Template". (Make sure you close the sidebar first by clicking the "hamburger" button at the top-left corner, or krystal's story-river width will be reduced.) Or,

- To lighten the size of your wiki, you can use a separate wiki that contains only this theme to create a color palette to your liking, then import the desired palette tiddler(s)&mdash;search for `$:/palettes/CaptivateDark`, `$:/palettes/CaptivateLight`, and `$:/palettes/CaptivateTan` tiddlers&mdash;into wikis that contain the krystal plugin only.  Switch the palette from the Control Panel > Appearance > Palette. This approach may not work as well as above because it lacks some of the theme tweaks, but you may find that it's sufficient for your purpose.
   
There are probably CSS adjustments you might need to make in either case. For example, if you'd like to color the topbar, you can create a tiddler tagged with `$:/tags/Stylesheet` and add the following:

```css
.krystal-header { 
  background-color: <<colour primary>>; 
}

.krystal-header .tc-site-title, 
.krystal-header .tc-site-subtitle,
.krystal-header .tc-btn-invisible svg, 
.krystal-header .tc-tiddlylink { 
    fill: <<colour on-primary>>;
    color: <<colour on-primary>>;
} 
```

Would these suggestions work for you?

**Comment by arunnbabu81** [comment]
The first suggestion works for me. Also i modified the topbar as suggested by you. Thanks for both.

Further i liked the search box in the topbar of your theme. I tried to change the default search in the topbar of krystal ($:/plugins/rmnvsl/krystal/search) with yours ($:/themes/cdr/captivate/ui/TopBar/Search)

But if I type something in that search box, the focus is lost from the search box while typing. Can you help about that. I have attached a demo wiki
[krystal.zip](https://github.com/cdruan/tw5-captivate/files/6993351/krystal.zip)

**Comment by cdruan** [comment]
The focus is stolen by another input box in the search dropdown. The fix is to prevent it from displaying. So here's the fix:

Add to your stylesheet:

```css
.krystal-header .cv-search-bar .tc-search { 
    display: none !important; 
}
```
